### ISSUE TITLE
Example Usage

### ISSUE THREAD

**Issue by bobhenkel** [snyk/snyk-cpp-plugin#17]
Could someone show an example of using this against a public github repo with cpp code?  I haven't been able to figure it out. I tried this on a file, but is it really scanning anything? If I change cpp to xyz it returns the same result.

```
bash-3.2$ snyk test cpp --file=Hello.cpp

Testing cpp...

Organization:      bob-playground
Package manager:   npm
Target file:      Hello.cpp
Open source:       yes
Project path:      cpp

✓ Tested cpp for known vulnerabilities, no vulnerable paths found.

Tip: Snyk only tests production dependencies by default. You can try re-running with the `--dev` flag.

bash-3.2$
```

Thanks
Bob

**Comment by anthogez** [comment]
@bobhenkel apologies for the late response here, as soon as the product 
is live its usage will be fully documented. Closing this issue.
